# Generated by Django 4.2.4 on 2023-12-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='cut_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='upload_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='regular_price',
            field=models.IntegerField(default=0),
        ),
    ]
