# Generated by Django 4.2.4 on 2023-12-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('author', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('blog_image', models.ImageField(upload_to='static/blog_images/')),
            ],
        ),
    ]
