# Generated by Django 4.2.4 on 2023-12-08 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_category_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_image',
        ),
    ]
